class EmbeddingModelMismatchException(Exception):
    """
    Raised when an embedding is created or consumed using a model that does not
    match the globally configured embedding model.

    This prevents mixing vectors generated by different embedding models or
    dimensions, which would break vector search consistency.
    """

    def __init__(self, expected_model: str, received_model: str):
        self.expected_model = expected_model
        self.received_model = received_model
        message = (
            f"Embedding model mismatch: expected '{expected_model}', "
            f"but received '{received_model}'. "
            "Ensure all services produce embeddings using the same model."
        )
        super().__init__(message)
