services:
  backend_db:
    image: postgres:16
    container_name: postgres-backend
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: backend_db
      TZ: Asia/Saigon
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  aimodule_db:
    image: postgres:16
    container_name: postgres-aimodule
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: aimodule_db
    ports:
      - "5433:5432"
    volumes:
      - aimodule_pgdata:/var/lib/postgresql/data

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - backend_db
    environment:
      DATABASE_URL: postgresql://backend_db:5432/backend_db
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin123
    ports:
      - "8080:3100"

volumes:
  pgdata:
  aimodule_pgdata:
